// Generated by component library do not modify
// can ge ignored by .gitignore
import ComponentsButton from './components/Button.react.js'

export default {
  ComponentsButton: {
    name: 'ComponentsButton',
    file: './components/Button.react.js',
    component: ComponentsButton,
    description: '',
    props: {children:{type:{name:"any"},required:true,description:""},disabled:{type:{name:"bool"},required:false,description:""},fullWidth:{type:{name:"bool"},required:false,description:""},inheritedStyle:{type:{name:"object"},required:false,description:""},kind:{type:{name:"enum",value:[{value:"'primary'",computed:false},{value:"'secondary'",computed:false},{value:"'outlined'",computed:false}]},required:true,description:""},onClick:{type:{name:"func"},required:false,description:""},size:{type:{name:"enum",value:[{value:"'small'",computed:false},{value:"'large'",computed:false}]},required:false,description:""},type:{type:{name:"string"},required:false,description:""}} // eslint-disable-line
  },
}
