// Generated by component library do not modify
// can ge ignored by .gitignore
import ComponentsButton from '../components/Button.react.js'
import ComponentsIcon from '../components/Icon.react.js'
import ComponentsRadioInput from '../components/RadioInput.react.js'
import ComponentsTooltip from '../components/Tooltip.react.js'

export default {
  ComponentsButton: {
    name: 'ComponentsButton',
    file: '../components/Button.react.js',
    component: ComponentsButton,
    description: '',
    props: {children:{type:{name:"any"},required:true,description:""},disabled:{type:{name:"bool"},required:false,description:""},fullWidth:{type:{name:"bool"},required:false,description:""},inheritedStyle:{type:{name:"object"},required:false,description:""},kind:{type:{name:"enum",value:[{value:"'primary'",computed:false},{value:"'secondary'",computed:false},{value:"'outlined'",computed:false}]},required:true,description:""},onClick:{type:{name:"func"},required:true,description:""},size:{type:{name:"enum",value:[{value:"'small'",computed:false},{value:"'large'",computed:false}]},required:false,description:""},type:{type:{name:"string"},required:false,description:""}} // eslint-disable-line
  },
  ComponentsIcon: {
    name: 'ComponentsIcon',
    file: '../components/Icon.react.js',
    component: ComponentsIcon,
    description: '',
    props: {color:{type:{name:"string"},required:false,description:""},display:{type:{name:"string"},required:false,description:""},inheritedStyle:{type:{name:"object"},required:false,description:""},kind:{type:{name:"enum",value:[{value:"'check'",computed:false},{value:"'star'",computed:false}]},required:true,description:""},size:{type:{name:"string"},required:false,description:""}} // eslint-disable-line
  },
  ComponentsRadioInput: {
    name: 'ComponentsRadioInput',
    file: '../components/RadioInput.react.js',
    component: ComponentsRadioInput,
    description: '',
    props: {horizontal:{type:{name:"bool"},required:false,description:""},name:{type:{name:"string"},required:true,description:""},onChange:{type:{name:"func"},required:true,description:""},selected:{type:{name:"bool"},required:true,description:""},text:{type:{name:"string"},required:false,description:""},tooltip:{type:{name:"string"},required:false,description:""},value:{type:{name:"string"},required:true,description:""}} // eslint-disable-line
  },
  ComponentsTooltip: {
    name: 'ComponentsTooltip',
    file: '../components/Tooltip.react.js',
    component: ComponentsTooltip,
    description: '',
    props: {tooltip:{type:{name:"string"},required:true,description:""}} // eslint-disable-line
  },
}
