// DO NOT EDIT DIRECTLY! Generated by `gulp fontIcons` task

import Component from 'react-pure-render/component';
import Radium from 'radium';
import React from 'react';

const styles = {
  icon: {
    color: 'hsl(0, 0%, 25%)',
    fontFamily: 'font-icons',
    fontStyle: 'normal',
    fontVariant: 'normal',
    fontWeight: 'normal',
    lineHeight: 1,
    fontSize: '30px',
    textAlign: 'center',
    speak: 'none',
    textTransform: 'none',
    transition: 'color .2s, transform .2s',
    userSelect: 'none'
  }
};

export const iconList = {
  check: '&#57345;',
  star: '&#57346;'
};

@Radium
export default class Icon extends Component {

  static propTypes = {
    color:          React.PropTypes.string,
    display:        React.PropTypes.string,
    inheritedStyle: React.PropTypes.object,
    kind:           React.PropTypes.oneOf([
      'check',
      'star'
    ]).isRequired,
    size:           React.PropTypes.string
  }

  render() {
    const {kind, color, size, display, inheritedStyle} = this.props;

    return (
      <div
        dangerouslySetInnerHTML={
          {__html: iconList[kind]}
        }
        style={[
          styles.icon,
          inheritedStyle,
          {
            color: (color || styles.icon.color),
            display: (display || styles.icon.display),
            fontSize: (size || styles.icon.fontSize)
          }
        ]}
      />
    );
  }
}
