import {Component} from 'react';
import React from 'react';

export default class Icon extends Component {

  static propTypes = {
    color:          React.PropTypes.string,
    display:        React.PropTypes.string,
    height:         React.PropTypes.number,
    inheritedStyle: React.PropTypes.object,
    kind:           React.PropTypes.oneOf([
      'check',
      'star'
    ]).isRequired,
    size:           React.PropTypes.string,
    width:          React.PropTypes.number
  }

  static defaultProps = {
    size:  32,
    color: 'hsl(0, 0%, 25%)'
  }

  render() {
    const {kind, color, size, height, width} = this.props;

    /* eslint-disable react/jsx-sort-props */
    // Generated by http://react-svg-icon-live-generator.herokuapp.com/
    switch (kind) {
      default: return null;
      case ('check'): return (<svg xmlns="http://www.w3.org/2000/svg" fill={color} height={height || size} width={width || size} viewBox="0 0 512 512"><path d="M433.998 71.678l-259.404 259.41-96.327-96.924-65.785 65.782 160.67 160.672L497.967 135.8z"/></svg>);
      case ('star'): return (<svg xmlns="http://www.w3.org/2000/svg" fill={color} height={height || size} width={width || size} viewBox="0 0 512 512"><path d="M503.747 201.027c0-8.946-9.542-12.524-16.698-13.717l-149.69-21.768-67.093-135.675c-2.684-5.666-7.753-12.226-14.61-12.226s-11.93 6.56-14.612 12.227l-67.092 135.675-149.69 21.768c-7.456 1.193-16.7 4.77-16.7 13.717 0 5.367 3.877 10.437 7.456 14.313L123.56 320.9 97.913 469.99c-.298 2.09-.596 3.878-.596 5.965 0 7.753 3.876 14.91 12.524 14.91 4.174 0 8.05-1.49 11.927-3.58l133.885-70.37 133.886 70.37c3.58 2.09 7.754 3.58 11.93 3.58 8.646 0 12.225-7.157 12.225-14.91 0-2.087 0-3.876-.298-5.964L387.752 320.9 495.994 215.34c3.877-3.877 7.753-8.946 7.753-14.313z"/></svg>);
    }
    /* eslint-enable react/jsx-sort-props */
  }

}
